name: V-Shop CI/CD Quality Gate

on:
  push:
    branches: [ main ]

jobs:

  commit_stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pytest
        run: pip install pytest

      - name: Run Unit Test
        run: pytest

  acceptance_stage:
    needs: commit_stage
    runs-on: ubuntu-latest

    steps:
      - name: Functional Test
        run: echo "Functional tests passed"

      - name: Performance Test
        run: |
          echo "Running performance test..."
          RESPONSE_TIME=150

          if [ "$RESPONSE_TIME" -gt 200 ]; then
            echo "Performance test FAILED"
            exit 1
          fi

          echo "Performance test PASSED"

      - name: Chaos Engineering Test
        run: |
          echo "Simulating service failure..."

          SERVICE_STATUS="UP"

          if [ "$SERVICE_STATUS" = "DOWN" ]; then
            echo "Service failed → FAIL"
            exit 1
          fi

          echo "Service recovered successfully"

  release_stage:
    needs: acceptance_stage
    runs-on: ubuntu-latest

    steps:
      - name: Build Release Candidate
        run: echo "Release Candidate Created"
